# This file was generated by GoReleaser. DO NOT EDIT.
class GoSemver < Formula
  desc "A tool to manage semantic versioning of software"
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pinterb/go-semver/releases/download/0.0.2/go-semver_darwin_amd64.tar.gz"
    sha256 "0166eef72352f84bb1534a1f23ee124ba79d248d2bb3e8a4fb8f92ba77bc15a3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pinterb/go-semver/releases/download/0.0.2/go-semver_linux_amd64.tar.gz"
      sha256 "aa5cebd5960e6428dff9c443e5af606cd1cb8d5edac2be0feb12f88873f39534"
    end
  end

  def install
    bin.install "semver"
  end

  test do
    system "#{bin}/semver version"
  end
end
