# This file was generated by GoReleaser. DO NOT EDIT.
class GoSemver < Formula
  desc "Get the contributor stats summary from all repos of any given organization"
  homepage ""
  version "0.0.2-rc.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pinterb/go-semver/releases/download/0.0.2-rc.0/go-semver_0.0.2-rc.0_darwin_amd64.tar.gz"
    sha256 "383149b3812972cac39f208fd3eb8aee662084e93da5d85e27d4146df9a307cb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pinterb/go-semver/releases/download/0.0.2-rc.0/go-semver_0.0.2-rc.0_linux_amd64.tar.gz"
      sha256 "229488e9fc5285d806df0e18ec2d43def1167c22af994405a5dd2fbe6075909a"
    end
  end

  def install
    bin.install "semver"
  end
end
